class AddScheduleElements:
    ScheduleTab = "/html/body/app-root/app-schedule-new/div/div[1]/app-nav-bar/div[3]/ul/li[4]/p"
    AddScheduleButton = "/html/body/app-root/app-schedule-new/div/div[2]/div/div[2]/schedule-screen/article/section[1]/article/div[2]/button/p"
    ScheduleName = "shift-name"
    ScheduleDescription = "shift-desc"
    ScheduleTimingClick = "/html/body/app-root/app-schedule-new/div/div[2]/div/div[2]/schedule-screen/app-schedule-modal/div/div[2]/div/div/div/div/div[2]/div[3]/div[2]/button/p"
    ScheduleStartTime = "/html/body/app-root/app-schedule-new/div/div[2]/div/div[2]/schedule-screen/app-schedule-modal/div/div[2]/div/div/div/div/div[2]/div[3]/div[2]/app-time-picker/div/div[1]/div[1]/div/div[10]"
    ScheduleStartTimeOkButton = "/html/body/app-root/app-schedule-new/div/div[2]/div/div[2]/schedule-screen/app-schedule-modal/div/div[2]/div/div/div/div/div[2]/div[3]/div[2]/app-time-picker/div[1]/div[2]/button"
    ScheduleEndTime = "/html/body/app-root/app-schedule-new/div/div[2]/div/div[2]/schedule-screen/app-schedule-modal/div/div[2]/div/div/div/div/div[2]/div[3]/div[2]/app-time-picker/div/div[1]/div[1]/div/div[7]"
    SelectEndPM = "/html/body/app-root/app-schedule-new/div/div[2]/div/div[2]/schedule-screen/app-schedule-modal/div/div[2]/div/div/div/div/div[2]/div[3]/div[2]/app-time-picker/div/div[1]/div[3]/div/button[2]"
    ScheduleEndTimeOkButton = "/html/body/app-root/app-schedule-new/div/div[2]/div/div[2]/schedule-screen/app-schedule-modal/div/div[2]/div/div/div/div/div[2]/div[3]/div[2]/app-time-picker/div/div[2]/button"
    AddButton = "/html/body/app-root/app-schedule-new/div/div[2]/div/div[2]/schedule-screen/app-schedule-modal/div/div[2]/div/div/div/div/div[3]/button[2]"